### ISSUE TITLE
s2, task 2

### ISSUE THREAD

**Issue by MattiWe** [MattiWe/safe-secure-supergroup#1]
TODO:
Ausgabe formatieren in deck.adb

**Comment by KujaEx** [comment]
Les heute noch die Kapitel fertig, kann ich aber morgen machen. Mit Ausgabe formatieren meinst du z.B. 1 -> Ace oder 12 -> Queen? Dann wäre es wohl besser Card_Type wie Suit_Type zu definieren, aber mit ( (Ace, 2, 3, 4, 5, 6, 7, 8, 9, 10, Jack, Queen, King). 
Es wird glaub auch nicht überprüft, ob sich eine Karte wiederholt, also ob alle 3 unique sind. Kann ich auch dazu coden, wenns okay.

**Comment by MattiWe** [comment]
theoretisch ja, aber die karten haben ja eigentlich nen numerischen wert 
-> designen wir die klasse so als hätte sie auch ne funktion

**Comment by MattiWe** [comment]
Am besten wäre es, wenn wir das ganze deck generieren/shuffeln, wenn wir das Objekt instanziieren

**Comment by KujaEx** [comment]
Ja, wenn du den numerischen Wert behalten willst, müsste man nur ein if/case zur print ausgabe hinzufügen für die 4 Ausnahmen. 
Mit Deck generieren, meinst du ne Liste(Array) erstellen mit den 3 Karten?

**Comment by MattiWe** [comment]
ne, das ganze deck (alle 13*4 kombinationen) generieren und auf einen stack pushen, shuffeln und dann 3 karten ziehen (pop)

**Comment by KujaEx** [comment]
mh, das würde dem echten zwar näher kommen, aber soviel ich weiß hat ADA kein benutzbaren Stack, man müsste also eine adb dazu selber machen oder ausn Internet nehmen.
Ich würde vorschlagen: wie du bereits sagtest alle 52 Karten zu generieren in ein array (=deck), ne funktion zu schreiben "show 3 random cards" und in der Funktion dann 3 unique random numbers (1~52) zu erzeugen und die entsprechenden 3 Karten dann anzuzeigen.
Wenns recht ist, würde ich es dann morgen so reincoden.

**Comment by MattiWe** [comment]
jo alles klar!

**Comment by MattiWe** [comment]
hab nochmal gegoogelt, es gibt in Ada auch std-container: https://en.wikibooks.org/wiki/Ada_Programming/Containers
--> wir können alle 52 Karten in nen Vector packen und dann dann loop: RNG(vector.size) -> stack-push -> vector.pop

**Comment by KujaEx** [comment]
Ja, das müsste gehen^^
Würde ich dann morgen so implementieren.

**Comment by KujaEx** [comment]
So, fertig. Musste in deck.ads den den Untertyp "Card" von "Card" umbenennen (-> habs "Value" genannt) weil es sonst Konflikte gab, wenn man "Card" einer Funktion übergibt (konnte dies nicht richtig zuordnen). Ansonsten Vector integriert, zufällige Karte ziehen (und aus Deck entfernen), Karte richtig printen und schauen ob Deck leer ist. Müsste jetzt alles so richtig sein.

Kleine Sache nebenbei: Hab jetzt nur die .ads und .adb Datein hochgeladen. GPS scheint noch andere Datein zu ändern: https://picload.org/image/rdlpgplo/screenshot2016-10-2313.15.21.png wo scheinbar nur Meta/Protokoll Daten drin sind. Auf gitignore setzen?

**Comment by MattiWe** [comment]
Eigentlich hab ich bin/* in der gitignore, kA. warum er das ignoriert. 
Ansonsten, wenns läuft ist cool. Vielleicht sollten wir dann noch Tests schrieben um zu zeigen, dass die karten wirklich unique sind (nachdem wir das in der VL hatten).
