### ISSUE TITLE
Last Assignment

### ISSUE THREAD

**Issue by KujaEx** [MattiWe/safe-secure-supergroup#10]
Matti meinte er macht Task 2, ich hab grad Task 1 angefangen (mit erweiterten Euklidischen Algorithmus). Nathalie hat also noch die freie Auswahl bei Task 3 und 4^^

**Comment by MattiWe** [comment]
Am besten beide :D

**Comment by KujaEx** [comment]
Ja :D 

Hab die 1 angefangen, und die Funktionen auch zum Teil implementiert (bzw. lokal da liegen, nicht alles hochgepusht), aber wie tut man das  Galois Field (in der Main) initialisieren? Habs auf zwei Arten probiert... weil das schon wieder ein genric ist, weiß ich nicht, wie ich den Typen "überschreiben" soll.

Wisst ihr, wie man in der Main (mit dem vorgegebenen .ads) das Galois Field erstellt?

**Comment by MattiWe** [comment]
Hab die 2 fertig.
Werden wahrscheinlich keine 4/4 weil ich zu faul bin für umfassendes testen, aber 3 bis 3.5 sind drin.

**Comment by KujaEx** [comment]
Hab heute noch mal mit Eik gesprochen (worauf er auch die Mail rausgeschickt hat). Die Aufgabe 1 hat sich als schwerer herausgestellt, als gedacht. Hab versucht alle Funktionen so zu implementieren, wie Eik es mir (bzw in der Mail) erklärt hat, aber es gibt auch kaum Lösungen, dass man testen könnte, ob die Funktionen so richtig sind. Hab meine jetzige Implementierung hochgeladen. Werde am Wochenende noch versuchen ein paar Tests zu schreiben.

**Comment by KujaEx** [comment]
Hab nochma kleine Bugs entfernt und Tests geschrieben. Bin mir nicht wirklich sicher, ob die Funktionen alle 100% richtig sind... musste auch mit Tests etwas hin und her probieren, bis ich richtig funktionierende gefunden hab (wir haben ja auch keine Testcases bereit gestellt bekommen für die Aufgabe).
Ich geh irgendwie bei der Aufgabe von 3/4 Punkten aus :/
Wenn Mattis auch nur 3 bringt, wären wir bei 6/20 insgesamt... das wäre ne echt knappe Angelegenheit  ._.''

**Comment by NaNaDi** [comment]
Ich sitze ja auch noch an der Aufgabe 4. Die gibt insgesamt 8 Punkte und auch wenn ich nicht die volle Punktzahl schaffen sollte, glaube ich auch nicht, dass wir aus der Aufgabe mit 0 Punkten raus gehen ;)

**Comment by NaNaDi** [comment]
Aufgabe 4 ist fertig, wir sollten also definitv auf die benötigte Punktzahl kommen ;)

**Comment by NaNaDi** [comment]
Habe unsere Lösung gerade Eik geschickt, gleich ist ja schon Abgabe ;)

**Comment by KujaEx** [comment]
Wir habens gesehen^^
Matti wollte glaub noch was schnell ändern bei Task 2... aber wenn du sicher bist, dass Task 4 bei dir funktioniert, sollten wir wohl genug Punkte bekommen.
Bei Task 1 gabs noch viel Diskussion, weil Gerrit und Max andere Versionen (als ich) gemacht haben, die angeblich funktionieren (zumindest mit den Wikipedia Beispielen), aber nach Eik völlig falsch implementiert sind (hab mich da mehr an seine e-mail gehalten). Mal sehn was Eik da heute präsentiert - wird wohl auch für viel Verwirrung sorgen^^'
