### ISSUE TITLE
s2, task 3 assertions

### ISSUE THREAD

**Issue by MattiWe** [MattiWe/safe-secure-supergroup#2]
Ich habe für Withdraw beispielhafte Pre und Postconditions eingebaut. Im normalfalle passiert aber nichts, selbst wenn man dagegen verstößt. Mit <pragma Assertion_Policy (Check);> kann man aber anschalten, dass ein Assertion_Error geworfen wird, wenn gegen die Conditions verstoßen wird. 
TODO:
- catch Assertion_Error
- Conditions für die anderen Methoden

**Comment by KujaEx** [comment]
Hab n paar Pre Posts hinzugefügt. Wollte erst noch sowas hinzufügen wie Amount >= Cents_Type'Last, aber das ist natürlich eher sinnlos, da die Grenzen der Typen ja schon von ADA selber überwacht werden. In der Main habe ich alle Funktionen getestet und dann absichtlichen Fehlaufruf eingebaut, sodass eine Assertion geschmissen wird:
raised SYSTEM.ASSERTIONS.ASSERT_FAILURE : failed precondition from bank_accounts.ads:19
