### ISSUE TITLE
s2, task5

### ISSUE THREAD

**Issue by KujaEx** [MattiWe/safe-secure-supergroup#3]
Ich muss ehrlich sagen, ich versteh den vorgegebenen Aufbau des Programms nicht. Ich würde einen Graphen doch entweder (a) in einer Matrix speichern oder (b) nur in einer Edge-Liste mit den Elementen (Edge record: Vertex1, Vertex2, Weigth), aber wie soll man einen Graphen  nur mit einer Vertex-Liste speichern?
Es macht Sinn die Vertices als generic zu haben, damit man alles mögliche als Punkte nehmen kann, aber mit "type Edge_Type is private ;" allein kann ich nichts anfangen.
Also wenn man Edge als record mit den 3 Elementen ausdrückt (b) dann ist der Rest des Programms auch leicht umzusetzen (nur Vector-Iterationen und schauen ob was da ist).

Was meint ihr dazu?

**Comment by MattiWe** [comment]
* adjazenz-matrix macht mit arrays keinen sinn, da haste zu viele freie felder
* nur Edge-List passt nicht so gut ins Programm --> add_vertex() wäre dann sinnlos (ist das dann from- oder to-vertex? ist weight=0 valide?)  Was passiert mir vertex_already_in_graph?
* Ich denke 2 Listen sind am flexibelsten, aber wir sollten beides in linked-lists schreiben, dann haben wir die geringste komplexität beim add-remove

**Comment by KujaEx** [comment]
Ob Linked-List oder Vector wird keine große Rolle spielen, da man bei beiden x-beliebige Elemente leicht entfernen kann...

Den Edge-Typ würde ich so machen und in einen Vector hauen:
type Edge_Type is
      record
         Vertex_1 : Vertex_Type;
         Vertex_2 : Vertex_Type;
         Weigth : Integer;
      end record;

Müssen die Vertices echt in nem Array sein? Soviel ich gelesen hab, kann man die Größe von dem Array nicht mehr ändern, sobald es initialisiert ist. Und die derzeitige Add-Vertex Funktion macht auch nicht wirklich was...

Und wie benutzt man ein generic in der main? Jedes mal wenn ich das Graph Package verwenden will, kommt die Fehlernachricht, dass es erst instantiiert werden muss... aber dazu find ich im Internet fast gar nichts... außer vielleicht sowas:
"package Integer_Graph is new Graph(Vertex_Type => Integer);" 
aber das scheint in der Main auch nicht so richtig zu funktionieren...

Verstehst du wie das alles funktionieren soll? Wenn nicht, ich treff am Montag Rene, der hat den Kurs schon abgeschlossen. Da kann ich ihn mal fragen, wie er das mit Generics gemacht hat.

**Comment by KujaEx** [comment]
Rene konnte ich erst heute sprechen, aber scheinbar haben die letztes Jahr gar nicht soviel in ADA gemacht mit Generics. War dann noch mal bei Jakob im Büro und hab nachgefragt:
1) Das man es nicht in Main aufrufen kann (bei mir der Fehler) lag daran, dass man nicht nur für den Vertices Type etwas übergeben muss, sondern auch dem "=" Operator, also wie:
package Integer_Graph is new Graph(Vertex_Type => Integer, "=" => "=");
(Da muss man erstma drauf kommen :/)
2) Hab gefragt, ob wir auch ein ein Vertex_Vector nehmen können, anstatt einen Vertex_Array (wegen Element hinzufügen, was viel einfacher wäre). Er hat zugestimmt, wir müssen nur als Kommentar dazu schreiben warum wir es von Array -> Vector geändert haben.

Können wir uns vielleicht Mittwoch oder Donnerstag irgendwann zusammen treffen, um das Programm fertig zu machen? Derzeit wirft es bei mir (lokal) nur Fehler, weil die Methoden noch nicht implementiert sind.

**Comment by MattiWe** [comment]
das mit dem =-operator steht glaub ich auch im script.

Ich wollte eigentlich 2 Klassen schreiben -> eine mit 2 nativen arrays und eine zweite mit nur Edge-Vector und dann ne Reihe von Tests um zu schauen was performanter läuft.

Ich schau morgen nochmal rein und sag dir dann nochmal, ob wir uns nochmal treffen wollen/sollten.

**Comment by KujaEx** [comment]
Beim zweiten meinst du Edge-Vector und Vertices-Vector, oder? Ein Vertices Vektor( oder Array) muss drin sein, weil das so vorgegeben ist.
Ja, wenn du das machen willst... kann mir kaum vorstellen, dass ein Array, was man ständig neu erstellen muss, performanter ist.
Naja, vergiss nicht, dass das Mini-Projekte bis Freitag 12:00 abgegeben werden müssen (Rest des Belegs Samstag 12:00). Ich hab mehr oder weniger den ganzen Mittwoch und Donnerstag Zeit.

**Comment by MattiWe** [comment]
das zweite machen wir ja um auf die vorgaben zu scheißen :D
Ich mach jetzt erstma die erste Klasse streng nach vorgabe fertig, schau du mal das die anderen beiden Aufgaben abgabereif sind :D

**Comment by KujaEx** [comment]
Hab jetzt nochma task 2 und 3 geupdated.

Bei Task 2 wäre es am einfachen einen Handkarten-Vectorin der Main zu haben und einfach beim Kartenziehen zu schauen, ob man diese Karte nicht schon im Vektor hat. Dafür muss man aber im Vector den "=" für "Card" definieren und das hab ich einfach nicht hinbekommen, ständig nur Fehlermeldungen. Also hab ich die Funktion "Compare_Cards(Card1, Card2)" geschrieben und mit dieser in der Main geschaut, ob die 3 Karten unterschiedlich sind - sollte aufs gleiche hinauskommen.

Bei Task 3 hab ich nur eine Pre-Condition hinzugefügt, die wir heute in der Vorlesung gesehen haben, also dass bevor man die Addition macht (Deposition) man schaut, nicht über die Zahlengrenze des Types zu kommen.

Damit sollten die Tasks 2 und 3 bei weitem erfüllt sein.

btw: Die testgen source zum Testen, die uns Eik/Jakob vorgestellt haben, lässt sich nicht richtig runterladen, bzw. kommt eine Fehlermeldung wenn man sie entpacken will. Hab den beiden schon ne Mail deswegen geschickt.

**Comment by KujaEx** [comment]
Hab mir grad jetzigen Stand angeschaut. Hast du die Methoden getestet? Bei mir wirft es zum Beispiel einen Fehler weil Edge_Type am Ende der .ads definiert ist, und deshalb für das Array unbekannt ist.

**Comment by MattiWe** [comment]
ja ich bin eh dran xD
Arrays sind so kompliziert mit den generics zusammen, kein vergleich mit Java ...
btw. geht das mit dem "dynamischen Vergrößern" der Arrays nicht, weil Ada Arrays per value assigned und nicht per reference --> Array-Szie muss am anfang schon feststehen
Ich denke in ner Stunde bring ichs zum laufen.

**Comment by MattiWe** [comment]
k läuft jetzt mit arrays, hab alles in der main getestet was geht. 
Ich setzt mich jetzt an die "advanced"-version
Kannst du nochmal wegen den Tests schaun ob wir das wirklich nicht zum laufen kriegen?
Ansonsten: kannst du es morgen zwischen 10 und 12 Abgeben? Ich hab dann vr ab 11oo ._.

BTW. Matrikelnummern und Namen: 

Matti Wiegmann, 112174
Nathalie Dittrich, 123456

muss noch irgendwo rein ;D

**Comment by KujaEx** [comment]
Ja, Abgabe kann ich machen mit allen 3 Aufgaben. Zwischen 11 und 12 Uhr, wenn ich aus VR raus bin^^'
(btw: soviel ich von Tim gehört hab, wird er wohl für beide VR Gruppen einen 1,5h Vortrag jeweils halten xD)

Mit den Tests wird jetzt kurzfristig nichts mehr. Allein die Anleitung ist über 10 Seiten lang. Da muss man sich auch etwas erst einarbeiten.
Von Rene hab ich gehört, dass er zum Testen das Framework Testgen von Luchs auch für 70% seiner Belege verwendet hat... nur bei den letzten Belegen, wo man Zeile für Zeile den Code testen muss, muss man später AUnit verwenden - da führt kein Weg dann mehr drum rum... soll auch recht aufwendig sein dann.

**Comment by KujaEx** [comment]
Da in der jetzigen Sms_Graph Version noch Fehler sind, geh ich mal davon aus, dass du noch dran codest?

Wollte nur noch sagen, nicht zu vergessen in der main.adb die procedure main in "Main" umzubennen. Eik/Jakob wollen alle Packages und Procedures/Functions mit Großbuchstaben haben (und anstatt Java Camelcase ein "_" zwischen den Wörtern). Wegen diesen Formfehlern haben die mir 2 Punkte abgezogen im ersten Beleg -.- (+1 wieder dazu gerechnet, weil ich beim Tier-Ratespiel weitere Tiere hinzugefügt hab >,>)

**Comment by MattiWe** [comment]
okay, ich hab jetzz die alternativ-version mit arrays noch geschrieben und hochgeladen
Dazu aber!!!!!111!11!:
   pragma Suppress(Tampering_Check); in main.adb Zeile 8 stellt quasi concurrent modification exceptions aus -> ich lösche beim iterieren über den Vector das Element unter dem Iterator. I Suck. 

Außerdem:
Wäre nice wenn man irgendwie die max-size der Arrays beim initialisieren angeben könnte. 

Aber von mir aus können wir das so abgeben.
