### ISSUE TITLE
s3, tasks?

### ISSUE THREAD

**Issue by KujaEx** [MattiWe/safe-secure-supergroup#4]
Hab mir jetzt Exercise 3 angeschaut... und da sind ja nur bewertete Mini-Projects drin. Heißt das jetzt A) Das wir hier gar nicht abgeben müssen, weil alles optional ist oder B) Wir 1-2 Mini-Projects machen müssen, um auf die über 25% Punkte pro Beleg zu kommen? (Das wäre halt widersprüchlich zu der Aussage am Anfang des Semesters, dass man 2 Mini-Projects über das Semester machen muss, wenn man bei diesem Beleg praktisch dazu gezwungen wird)

Falls wir was machen müssen, würde ich halt Task 3 und 5 bevorzugen.

**Comment by MattiWe** [comment]
Wir können Task 3,4,5 machen, dann hat jeder nen eigenen :)
Ich würde gerne Task 3 machen um A-Unit zu lernen :D 
Ich mach gleich mal Projekte für die drei Tasks!

**Comment by KujaEx** [comment]
Ja, schau mir auch grad AUnit Tutorial an... ist schon ziemlich abfuck, was da alles drin ist und was man dafür erstellen muss.
Task 3 ist natürlich am einfachsten... wobei Eik den Code bisher (auf slides) nicht hochgeladen hat, aber das Projekt ja auch am einfachsten. Ich versuch dann erst mal 5 zu implementieren... ist ja eigentlich nur ein if-else-Gewirr.

**Comment by NaNaDi** [comment]
Dann kümmer ich mich um die 4 ;)

**Comment by KujaEx** [comment]
Also Task 5 hab ich programmtechnisch fertig gemacht, aber testgen funktioniert einfach nicht :/
Hab mit testgen.exe und test.ts die test.adb erstellt, in thread.gpr eingebunden:
for Main use ("main.adb, test.adb");
Und beim compilieren kommt erst mal der Fehler, dass folgendes fehlt:
with Ada.Text_IO; use Ada.Text_IO;
(Warum included dass die Test nicht selber, wenn es das braucht?)
Okay, also füg ich das oben hinzu und es kommen nur noch Warnungen. Wenn ich es dann durchführ macht die test.adb keinen Mucks. Muss sie nicht irgendwas ausgeben, wie "Test succeeded" oder so?

**Comment by MattiWe** [comment]
Main use ("main.adb, test.adb"); < musst du auch wirklich machen

**Comment by KujaEx** [comment]
for Main use ("main.adb", "test.adb"); meinte ich. hab ich auch lokal gemacht, sonst würde er die test.adb ja nicht compilieren. aber wenn mans ausführt kommt trotzdem nichts von der test.
Kannst du mit deiner testgen die test.ts umwandeln und dann in gps testen?

**Comment by MattiWe** [comment]
ja

**Comment by KujaEx** [comment]
Eik war grad bei uns (im webis lab) und hats sich angeschaut. Es scheint ein allgemeiner Fehler zu sein bzw. nur auf Windows:
1) Adde in der .ts file oder in der erstellten .adb file die imports: "with Ada.Text_IO; use Ada.Text_IO;"
2) Schalte in der .gpr file "-gnatwe" aus (falls es aktiviert ist). Diese wandelt warnings zu errors um, weshalb die compilierte .adb file dann keine Outputs macht

btw: André, Erdan und Co sind auch hin und hergerissen testgen oder AUnit zu verwenden. Mit Eik schaffen sie es gerade nicht auf Linux AUnit zum Laufen zu bekommen, sodass testgen wohl immernoch (trotz bugs) die bessere Alternative ist.

**Comment by MattiWe** [comment]
1+ 2 hab ich bei mir auch machen müssen im tg. Wenn du mit -gnatwe Warnings bekommst kompiliert das Project doch garnicht? Is ja kla das du keinen Output kriegst. 
Task3 is btw. fertig. 

Zu Windows vs. Linux -> Ich würde mir den Trouble ja geben, wenn ich mehr als 3 Stunden/Woche da dran arbeiten würde. Aber so ists mir nicht wichtig -> ergo ich machs einfach daheim aufm Desktop. Selbe für ACT-R und QGIS. Da dauerts 3x länger das aufzusetzen als es dauert, die Assignments zu machen.

**Comment by KujaEx** [comment]
So, hab test.ts noch einige test cases hinzugefügt... und wer hätts gedacht, sie haben mir geholfen einen Fehler in den Pre/Post Conditions zu finden xD (musste da S zu S'Old ändern). 
Task 5 ist jetzt komplett fertig^^ 
Hab auch den ganzen Testkram in nen src/test Unterordner ausgelagert (muss man nur in der .gpr anmelden dass es den Ordner gibt). Hab ich in anderen Projekten oft so gesehen. Jakob und Eik sehn das glaub auch so lieber, wenn der Testkram in nen seperaten Ordner ist.

**Comment by MattiWe** [comment]
supa, dann muss ja nur noch natalie delivern xD
Ja, das mit dem unterordner is eh nice, vll schau ich mir meins dahingehen nochmal an

**Comment by KujaEx** [comment]
side info: hab grad beleg 2 abgeholt, 12/20.
Warum so wenig? Naja, Vector hatten wir ja nicht gemacht und dann wurden so kleine Sachen bemängelt, wie das Card_Value enum besser wäre als 1~12 oder man bei return gleich ein boolean zurück geben kann anstatt erst if else zu fragen... alles so Kleinigkeiten wo er -0.5 Punkte abgezogen hat pro Aufgabe und damit kommen wir auf 12/20 am Ende ... was aber natürlich bei weitem über 25% ist und damit okay...

**Comment by MattiWe** [comment]
danke. Das mit dem Enum hatten wir ja eh besprochen, ich finde unsere Lösung trotzdem besseres Design.

**Comment by KujaEx** [comment]
Morgen (Montag) ist Abgabe. Soll ich sie wieder fertig machen? Ihr müsstet nur alles noch fertig commiten, falls noch was fehlt.

@NaNaDi:
Hab nur kurz über deinen Code geschaut. Da ist mir das aufgefallen:
function All_Voters_Voted return Boolean is
    begin
    	if Num_Votes_Made = Num_Total_Voters then
    		return TRUE;
    	else
    		return FALSE;
    	end if;
    end;

Ansich alles okay (so hab ich es im letzten Beleg auch mal bei mir programmiert), aber Eik hatte hier -0.5P abgezogen, weil man auch einfach schreiben könnte:
return Num_Votes_Made = Num_Total_Voters; (was genauso True oder False zurück gibt)

**Comment by MattiWe** [comment]
jo wäre nice

**Comment by NaNaDi** [comment]
Delivered! ;)

**Comment by NaNaDi** [comment]
Hat's schon jemand von euch abgeschickt?

**Comment by KujaEx** [comment]
So, habs jetzt abgeschickt. (siehe email)

Frage: Ihr habt neben eurer .gpr immer noch so eine 25kb "test" Datei. Hab die bei der Abgabe rausgenommen. Weiß auch nicht für was die gut sein soll?

**Comment by NaNaDi** [comment]
Die wird beim testen automatisch erzeugt, kannst die aber raus nehmen.
An der gpr habe ich eigentlich auch nichts gemacht. Arbeite immer mit Sublime und kompiliere es dann über die Konsole.

Aber danke für's Abschicken :)
