### ISSUE TITLE
Task 4 Test Cases

### ISSUE THREAD

**Issue by NaNaDi** [MattiWe/safe-secure-supergroup#5]
HeyHo :)
Ich habe mich endlich durch alles durchgewühlt und nun durchgeblickt wie das ganze Testen so läuft, aber leider habe ich schlichtweg keine Idee, was man bei der Aufgabe 4, also bei den Elections, testen könnte. Alles was mir einfällt liegt irgendwo im Rahmen des nicht machbaren. Hättet ihr zufällig ein paar realistische Vorschläge für Testcases, die ich hier umsetzen könnte?

**Comment by KujaEx** [comment]
Mh, Testcases sind hier etwas blöder zu schreiben, aber im Grunde testet man immer, ob der Output der Funktionen richtig ist. z.B.
- zuerst initialized du z.B. 5 total voters, machst dann 5 votes und schaust ob All_Voters_Voted true zurück gibt
-  initialized du z.B. 5 total voters, votest 3 mal für A, zwei mal für B und Find_Winner müsste A zurück geben
- Find_Winner muss None zurück geben, wenn 2 mehr Partein gleichviel Stimmen an höhster Stelle haben

Das wären schon mal 3 und von denen kannst du auch das Gegenteil testen.
Erdan hat für Aufgabe 5 auch alle möglichen tests erstellt (über 35) was mir zuviel ist. Naja, er muss es auch präsentieren.

**Comment by NaNaDi** [comment]
Dankeschön! Hab's jetzt so getestet :)
