### ISSUE TITLE
Assignment 4

### ISSUE THREAD

**Issue by KujaEx** [MattiWe/safe-secure-supergroup#6]
Hab heut versucht task2 zu machen auf Thread. Zuerst hab ich in der Konsole durchgeführt:
gnatmake -P my_thread.gpr -f -cargs -fprofile-arcs -ftest-coverage -largs -fprofile-arcs
was funktioniert hat und die .gcno bzw. immer updatende .gcda wurden erstellt, aber was dann? Hab versucht gcov test.gcda (oder .gnco) aber es kommt immer nur die Fehlermeldung "out of memory allocating 98439632 bytes"

Läuft es bei euch?

Edit:
Okay, seh grad, in Eiks slides wirds anders erklärt. Hab mich an die Beschreibung von der gcov Seite gehalten, was scheinbar nicht so richtig funktioniert. Probiers morgen nach Eiks Anleitung.

**Comment by KujaEx** [comment]
Nach Eiks slides gehts irgendwie noch weniger. Hab gegoogelt und mein Problem mit  "out of memory allocating 98439632 bytes" scheint an der gcc Version zu liegen...
Bin die nächsten zwei Tage mit Cognitive Systems voll beschäftigt. Werde mich Mittwoch wohl mal an task 3 setzen.
Könnt ihr schauen ob task 2 bei euch läuft? (Eigentlich einfache Aufgabe, wenns nur laufen würde u__u)
Ansonsten könnten wir uns auch mal Mittwoch, Donnerstag, Freitag oder Sonntag treffen für die Aufgaben (Samstag nicht, bin ich auf Treff :D)

**Comment by MattiWe** [comment]
Ich schau mir die 2 mal an

**Comment by MattiWe** [comment]
bin mit der 4 fertig

**Comment by KujaEx** [comment]
Schön. Wie vllt gesehen hab ich die 5 angefangen, und ich denk ich werd sie auch am Sonntag fertig bekommen.
Und ja, die 2 hab ich auch aufgegeben... da läuft gar nix dran, vllt gibts da auch deshalb nur so wenig Punkte, weil sie davon ausgegangen sind, dass es wieder nicht bei jedem laufen wird.

**Comment by MattiWe** [comment]
das wäre sowohl bad als auch awesome design ...

**Comment by NaNaDi** [comment]
Hey :)
Sorry, dass ich mich so spät melde.
Was genau gäbe es noch zu tun? Dann kann ich mich morgen mal da dran setzen ;)

**Comment by MattiWe** [comment]
2 und 4. gl!

**Comment by NaNaDi** [comment]
Okay ;)

**Comment by NaNaDi** [comment]
Kann es sein, dass jemand von euch schon 4 a und b gemacht hat? Pre- und Post Conditions und def,p-use,c-use stehen da schon :D 
Dann kümmere ich mich mal um Hoare ;)

**Comment by NaNaDi** [comment]
Oh, Hoare ist da auch schon :D 
Na, dann spring ich mal zu Aufgabe 2 ;)

**Comment by MattiWe** [comment]
ja ich bin auch dumm, die 4 hab ich ja gemacht
2+3 ist noch offen

**Comment by KujaEx** [comment]
Hab jetzt 5 fertig implementiert, aber bekomms nicht in der main (bzw. halt dann auch als test) definiert. Ich versuchs so zu definieren in der main:
define package IBT is new Binary_Trees(Item_Type => Integer, "=" => "=", "<" => "<", Put_Item => Ada.Integer_Text_IO.Put);
Aber es meckert immer rum, dass es Put_Item so nicht definieren kann. Matti, du hast doch schon mal mit generics gearbeitet. Weißt du, was man da machen kann?

**Comment by MattiWe** [comment]
1. genaue Fehlermeldungen pls
2. Die zeile ist nur die definition der generics, das object musst du glaub ich nochmal extra instanziieren mit 
my_tree : Binary_Trees

**Comment by KujaEx** [comment]
1. "no visible subprogram matches the specification for "Put_Item""
2. Nee, weil in der Klasse nur die Methoden aufgerufen werden. Man brauch nur den Binary_Tree_Access Typen aus der Klasse (siehe main). Ich weiß nur nicht, was ich der Put_Item Methode übergeben soll. Die Standard Integer Put Methode nimmts ja nicht an.

**Comment by MattiWe** [comment]
hast du mal versucht n wrapper für int.put zu schreiben, der der deklaration entspricht?

**Comment by KujaEx** [comment]
Hab jetzt extra ne neue adb/ads geschrieben für Put_Integer. Der Fehler, dass es nicht gefunden wird, ist zwar nicht mehr da, aber immer noch (und den versteh ich nicht):  "declaration expected" bei der define Zeile (siehe neues commit). Was ist hier falsch?

`with Ada.Text_IO;
with Put_Integer;
with Binary_Trees;

procedure Main is

   define package IBT is new Binary_Trees(Item_Type => Integer, "=" => "=", "<" => "<", Put_Item => Put_Integer.Put);
   My_Tree_Pointer : IBT.Binary_Tree_Access := null;

begin
   Ada.Text_IO.Put_Line("Start program");
   My_Tree_Pointer := IBT.Create(7);
   IBT.Add_Item(My_Tree_Pointer, 5);
   IBT.Put(My_Tree_Pointer);
   Ada.Text_IO.Put_Line("End program");
end Main;`

**Comment by KujaEx** [comment]
Okay, jetzt funktionierts. das define war noch aus der Testschreibweise. Jetzt sollte alles gehen^^'

**Comment by KujaEx** [comment]
Hab nun auch tests fertig. Alles läuft mit task 5!
Hab nur bei einer Funktion nicht alles 100%ig implementiert. Bei der Funktion "Remove_Item", der Fall dass man einen node löschen will der zwei Kinder hat, in dem Fall hab ich einfach beide Kinder (und Kindeskinder) gekillt. Ist eigentlich nicht der richtige Weg... man müsste hier neue Fälle machen und eins der Kinder mit dem Parent austauschen und komplett neu anlegen... aber das wurde mir zu konfus, weshalb ich den einfachen Weg genommen hab^^' Hoff mal das stört Eik an der Stelle nicht, ansonsten zieht er vllt 0.5P ab da ._.''

Soll ich morgen wieder den ganzen Kram zusammen abgeben von 11~12 Uhr?

**Comment by NaNaDi** [comment]
Die Aufgabe 2 ist echt scheiße, vor allem weil bei der Thread-Geschichte auf wieder mein legendärer gnutbug kommt :D 
Aber die 3 müsste soweit fertig sein, inklusive Bonustask ;)
Könnt ja mal 'nen Blick drauf werfen, ob ihr denkt das ist gut so ;)
Hab die Pre- and Postconditions auch nur als Kommentar unten dran gehängt, da das ja kein wirkliches Package ist. Das dürfte aber kein Problem sein, solange die ordentlich formuliert sind, denk ich mal ;)

**Comment by KujaEx** [comment]
Hab kurz drüber geschaut... aber da ich mir die Aufgabe nicht so angeschaut hab, kann ich nichts zu Richtigkeit sagen. Scheint aber okay zu sein :D 
Also kann ich jetzt abgeben? Da wir zu 2 keiner was richtig zu Stande bekommen hat (weder richtige HTML-Ausgabe noch Code Coverage > 95%), geb ich dazu auch nichts ab. Zu 5 die ich gemacht hab, glaub ich sollten es ca. 4 von 5 Punkten mindestens sein. Mit den Hoare Logic Aufgaben, die ihr gemacht habt, sollten wir eigentlich locker über die 4,5 Punkte kommen, die wir für die 25% brauchen^^

(>^o^)> Also geb ich dann mal jetzt ab <(^o^<)

**Comment by NaNaDi** [comment]
Super, danke! :)

**Comment by MattiWe** [comment]
Wow, wie du uns tatsächlich zutraust zusammen bei 2 Aufgaben 0.5 Punkte zu kriegen xD
/close
