### ISSUE TITLE
spark + threads

### ISSUE THREAD

**Issue by MattiWe** [MattiWe/safe-secure-supergroup#7]
Hey, 

Bei der Statemachine -> Soll die init-procedure den State nur dann auf Ready setzten, wenn er vorher None war? Oder soll Init die Statemachine immer auf Ausgangsposition setzten?

Es würde sinn machen als Pre => S = None zu haben, das ist aber in den Kommentaren zu Spezifikation nicht erwähnt. 
Was denkt ihr?

/edit und dazu kommt noch: was soll Do_Action(Action) machen, wenn State=null? State wieder auf Null setzen, oder soll der Fall durch Preconditions ausgeschlossen werden?

**Comment by KujaEx** [comment]
Sorry, seh jetzt erst den Post^^'

So wie Eik es glaub hatte, wird alles, was nicht definiert ist, weggefangen durch Pre-Conditions.

btw: Mini-Projekt fertig mit Tests und allem drum und dran! :D

**Comment by MattiWe** [comment]
ja aber bei Initialize steht ja nicht dabei, dass S'Old = None sein muss -> soll ich das annehmen für die Precondition, oder soll ich jeden Zustand von S zulassen?

**Comment by KujaEx** [comment]
Wenn ich das richtig verstanden hab, musste der Zustand None sein, damit man ihn auf Ready setzen darf. Alle anderen sind nicht erlaubt.

**Comment by MattiWe** [comment]
Wo steht das denn?

**Comment by KujaEx** [comment]
Wahrscheinlich wird da einfach gar nichts gemacht, werden nur ignoriert. Also keine Constraints dahingehend.
Aber frag doch Eik. Der antwortet immer ziemlich schnell.

**Comment by NaNaDi** [comment]
Heyho :)
Hattet ihr auch tausend Warnings beim Kompilieren vom Projekt?
Ich mache ja in Aufgabe 3 prinzipiell das Gleiche, wie in Aufgabe 2 bereits gemacht werden sollte. Normalerweise kompilliere ich meinen Kram immer über gnatmake. Das klappt auch soweit. Wenn ich jetzt aber versuche die main.gpr über gprbuild zum Laufen zu kriegen kommen tausend Warnings über verschiedene Variablen, die doch constant sein könnten und auch so testgen Sachen, wie dass zB. die Funktionen passed und failed nicht referenziert werden. Das hat ja konkret nichts viel mit der Aufgabenstellung zu tun, deswegen mal in die Runde gefragt: Hat jemand 'ne Idee, wie man das Problem löst? :/

**Comment by KujaEx** [comment]
Also wird wegen Warnings nicht kompiliert?
Seit 2-3 Belegen hab ich aus meiner .gpr das "-gnatwe" beim Compiler rausgenommen, weil die testgen erzeugten .adb files ständig sinnlose warnings schmeißen.
Du kannst dich an meiner task4.gpr orientieren, wenn du willst.

**Comment by NaNaDi** [comment]
Danke, das hat geholfen :)
Aber unter gnatprove kompilliert er mir nicht mit gprbuild... da kommt jedes Mal:

Phase 1 of 2: generation of Global contracts ...
gprbuild: illegal option "--no-exit-message" on the command line
gnatprove: error during generation of Global contracts

Wenn ich wüsste wo "--no-exit-message" steht, dass ich das rausnehmen kann... aber ich find's nicht und googlen lässt sich die Fehlermeldung auch nicht... :/

**Comment by KujaEx** [comment]
Kanns wieder nur mit meinem .gpr vergleichen, wo ich neben Compiler auch habe:
package Builder is
      for Default_Switches ("ada") use ("-g", "-gnat12");
   end Builder;
Weiß nicht, ob das wichtig ist. Kann mit der Fehlermeldung sonst auch nichts anfangen.

Will nur noch mal drauf hinweisen, dasss die Übung heute 15:15 stattfindet und ich deshalb zwischen 14-15Uhr alles abgeben würde.

**Comment by NaNaDi** [comment]
Ich hab Deine .gpr mehr oder weniger übernommen. Ich glaube ich mache mich sonst einfach mal auf den Weg zu Eik ins Büro. Die ganzen Globals und Depends und Invariants usw habe ich, das einzige was fehlt ist das doofe gnatprove... :/

**Comment by NaNaDi** [comment]
War heute bei Eik, er hat die main.gpr nochtmal etwas angepasst und abgeändert.
Der gnatprove-Fehler kam daher, dass gnatprove die Umgebungsvariablen nicht richtig gefunden hat, war also keine direkte Ada oder Spark - Geschichte.
gnatprove hat dann noch wegen ein paar Globals rumgemeckert, die ich hinzugefügt habe, jetzt kompilliert das aber nicht richtig, da steht dass die Variablen in 'ner dependency list sein müssen. Mein aktueller Stand ist kompilliert, es fehlt halt nur noch der gnatprove-Output.
Gebe bis 3 noch Gas, vllt findet sich doch noch 'ne Lösung, ansonsten müssen wir's so abgeben. Wäre zwar nicht volle Punktzahl, aber mit 0 Punkten würden wir sicherlich auch nicht aus der Ausgabe gehen.

**Comment by KujaEx** [comment]
Ich hab vor knapp 20min alles abgegeben, wie der aktuelle Stand war. Falls du noch was geändert hast bis um 3, müsstest du die Aufgabe (task3) neu gezippt an Eik schicken^^'

**Comment by NaNaDi** [comment]
Es funktioniert!!!!!!!! Habe nicht so ganz verstanden wieso, aber hab jetzt meine tollen gnatprove-Outputs :D 
Schicke Eik dann direkt nochmal als Nachtrag die Aufgabe 3 ;)

**Comment by NaNaDi** [comment]
14:59 Uhr abgegeben.
Achievement unlocked :D

**Comment by KujaEx** [comment]
Nee, das "Last Minute" Achievement gabs nur kurz vor 15:15, das war nämlich der Abgabeschluss :D 
Aber vergiss nicht, um zur mündlichen Prüfung zugelassen zu werden, musst du auch noch ein Mini-Projekt vorstellen... und es gibt nur noch 2 (3?) Belege^^

**Comment by NaNaDi** [comment]
Ooh verdammt, ich dachte es wäre 15:00 Uhr... habe noch nie so schnell 'ne eMail verfasst :D 
Hatte mich gestern Vormittag bereits bei Eik für die erste Mini-Projekt Vorstellung im neuen Jahr angemeldet ;)
