### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by NaNaDi** [MattiWe/safe-secure-supergroup#8]
Heyho :)
Zur allgemeinen Aufgabenaufteilung: Ich muss die Aufgabe 3 präsentieren, das heißt ich würde mich um diese Aufgabe kümmern ;)

**Comment by KujaEx** [comment]
Wie läufts mit deinem Mini-Projekt und Präsentation? (weil du noch keine commits gemacht hast^^')

Hab heute Aufgabe 2 fertig gemacht... hoffe ist alles richtig. Ihr könnt aber auch mal drauf schaun, wenn ihr wollt. Zumindest in Tests und so läuft alles ohne Probleme. Weiß nicht, ob ich gnatprove-mäßig alles richtig gemacht hab.

**Comment by NaNaDi** [comment]
Mit dem Mini-Projekt läuft's einigermaßen. Ich habe allerdings Probleme Variablen vom Typ Input_Type zu initialisieren bzw einen Integer in einen Input_Type umzuwandeln.
Hatte eigentlich auch schon in den Weihnachtsferien angefangen, aber meine Ergebnisse waren stets nicht "schön" genug um commitet zu werden ;)

Dein gnatprove-Output sieht meines erachtens nach ganz gut aus, ich sehe mich aber nicht gerade als gnatprove-Expertin an :D

**Comment by NaNaDi** [comment]
Okay, läuft jetzt :D 
Jetzt noch ein schönes Testskript und Folien und dann wird das schon was am Dienstag ;)

**Comment by KujaEx** [comment]
Morgen 11 Uhr ist Abgabe. Da ich davor eine Vorlesung habe, würde ich heute Abend gegen 23Uhr alles abgeben wie gewohnt per mail. Bitte schaut nach ob alles wichtige auf git liegt.

**Comment by NaNaDi** [comment]
Ich bin noch am werkeln. Kann morgen früh aber das ganze abgeben, dann musst Du das heute nicht machen und unsere Abgabe ist dann nicht so zerstückelt ;)

**Comment by KujaEx** [comment]
Danke! ( ´ ∀ `)ノ～ ♡
