### ISSUE TITLE
S6 - task 4

### ISSUE THREAD

**Issue by MattiWe** [MattiWe/safe-secure-supergroup#9]
Hey, 

ich hab den task 4 gemacht (d.h. er läuft unter Idealbedingungen durch) aber:

-> Ich habe keine Ahnung was passiert, wenn irgendwas mit den files nicht stimmt, aka type beim aufrufen, OUT-File gibts schon, IN-File ist nicht perfekt (z.b. ein nicht-Integer irgendwo im file)
-> atm. macht es einfach einen neuen task für jeden divide der list >> ist die liste 1000 zeichen lang, haben wir 1000 tasks. Besser wärs wenn wir genau soviele tasks machen wir die CPU threads hat. 

Ich habe aber kein bock mehr da noch weiter dran rumzuschrauben, hab eh schon zuviel zeit da reingeballert :D

Wenn ihr also Langeweile habt, könnt ihr noch n bisschen dran rumbasteln ;)

**Comment by NaNaDi** [comment]
Musst Du nicht eigentlich auch noch test cases schreiben für Deine Aufgabe? Zumindest Deine main.ts enthält momentan nur das standard-template.
Das mit den CPU-Threads klingt wirklich nach ordentlich Arbeit :D 
Aber so oder so sollten wir sicherlich die 25% bekommen ;)
